title: Meu Blog
description: Blog pessoal com projetos e informações de contato
theme: just-the-docs

url: https://gabrielramos731.github.io

aux_links:
  GitHub: https://github.com/gabrielramos731

# Include pages from _pages folder
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"
    
color_scheme: dark


